version: "3.9"
services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 main:app
    ports:
      - 5000:5000
    volumes:
      - .:/weather_app
    env_file:
      - ./.env
    environment:
      FLASK_DEBUG: "true"
  redis:
    image: "redis:alpine"
  # nginx:
  #   image: nginx:1.19.4
  #   depends_on:
  #     - web
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - '8080:80'